server:
  port: 9001    # 指定端口

spring:
  application:
    name: tensquare-base   # 模块名
  datasource:   # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.46.30:3307/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:      # 配置jpa
    database: mysql
    show-sql: true
  rabbitmq:
    host: 116.62.46.30
eureka:
  client:
    serviceUrl:
      defaultZone: http://116.62.46.30:6868/eureka/
  instance:
    prefer-ip-address: true


