server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:   # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.46.30:3307/tensquare_friend?characterEncoding=utf-8
    username: root
    password: root
  jpa:      # 配置jpa
    database: mysql
    show-sql: true
jwt:
  config:
    # 加盐
    key: maochaoying
    ttl: 3600000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问
